version: "3.8"

services:
  crtf-nginx:
    container_name: crtf-nginx
    build:
      context: ./proxy
      args:
        PROXY_KIND: obtain-certificates
        EXTERNAL_HTTP_PORT: ${EXTERNAL_HTTP_PORT}
        EXTERNAL_HTTPS_PORT: ${EXTERNAL_HTTPS_PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - ./proxy/storage/acme:/usr/share/nginx/acme
    ports:
      - "${EXTERNAL_HTTP_PORT}:${EXTERNAL_HTTP_PORT}"
  crtf-certbot:
    container_name: crtf-certbot
    image: certbot/certbot:latest
    env_file:
      - .env
    command: certonly --webroot --webroot-path=/usr/share/nginx/acme --staging --email="$EMAIL_USER" --agree-tos --no-eff-email -d "$SRV_NAME"
    volumes:
      - ./proxy/storage/acme:/usr/share/nginx/acme
      - ./proxy/storage/cert:/etc/letsencrypt
    depends_on:
      - crtf-nginx